name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Instala dependências
        run: npm install
      - name: Reinstala Jest (corrige permissões no Linux)
        run: npm install --force --save-dev jest
      - name: Roda os testes
        run: node ./node_modules/jest/bin/jest.js