name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Remove package-lock.json e node_modules
        run: |
          rm -rf node_modules
          rm -f package-lock.json
      - name: Instala dependências limpas direto no Linux
        run: npm install --no-package-lock
      - name: Instala Jest no Linux (garante permissão correta)
        run: npm install --save-dev jest
      - name: Lista arquivos e permissões do .bin
        run: ls -l ./node_modules/.bin
      - name: Testa Jest manual pelo shell
        run: ./node_modules/.bin/jest --version
      - name: Roda os testes via Node
        run: node ./node_modules/jest/bin/jest.js